//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTPagoElectronicoService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.pasarela.fasttrack.com.co/comercios", ConfigurationName="FTPagoElectronicoService.FTPagoElectronicoServicePortType")]
    public interface FTPagoElectronicoServicePortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="procesarPago_action", ReplyAction="http://service.pasarela.fasttrack.com.co/comercios/FTPagoElectronicoPortType/resp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FTPagoElectronicoService.procesarPagoResponse1> procesarPagoAsync(FTPagoElectronicoService.procesarPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="consultarEstado_action", ReplyAction="http://service.pasarela.fasttrack.com.co/comercios/FTPagoElectronicoPortType/resp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FTPagoElectronicoService.consultarEstadoResponse1> consultarEstadoAsync(FTPagoElectronicoService.consultarEstadoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.pasarela.fasttrack.com.co/comercios")]
    public partial class procesarPago
    {
        
        private PagoRequest pagoRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public PagoRequest PagoRequest
        {
            get
            {
                return this.pagoRequestField;
            }
            set
            {
                this.pagoRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.pasarela.fasttrack.com.co/comercios")]
    public partial class PagoRequest
    {
        
        private string usr_appsField;
        
        private string pwd_appsField;
        
        private string id_comercioField;
        
        private string usr_clienteField;
        
        private string fecha_transaccionField;
        
        private string fecha_canalField;
        
        private string url_comercioField;
        
        private string ip_clienteField;
        
        private string total_transaccionField;
        
        private string id_productoField;
        
        private Tercero terceroField;
        
        private Transaccion[] transaccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string usr_apps
        {
            get
            {
                return this.usr_appsField;
            }
            set
            {
                this.usr_appsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string pwd_apps
        {
            get
            {
                return this.pwd_appsField;
            }
            set
            {
                this.pwd_appsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string id_comercio
        {
            get
            {
                return this.id_comercioField;
            }
            set
            {
                this.id_comercioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string usr_cliente
        {
            get
            {
                return this.usr_clienteField;
            }
            set
            {
                this.usr_clienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fecha_transaccion
        {
            get
            {
                return this.fecha_transaccionField;
            }
            set
            {
                this.fecha_transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string fecha_canal
        {
            get
            {
                return this.fecha_canalField;
            }
            set
            {
                this.fecha_canalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string url_comercio
        {
            get
            {
                return this.url_comercioField;
            }
            set
            {
                this.url_comercioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ip_cliente
        {
            get
            {
                return this.ip_clienteField;
            }
            set
            {
                this.ip_clienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string total_transaccion
        {
            get
            {
                return this.total_transaccionField;
            }
            set
            {
                this.total_transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string id_producto
        {
            get
            {
                return this.id_productoField;
            }
            set
            {
                this.id_productoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public Tercero tercero
        {
            get
            {
                return this.terceroField;
            }
            set
            {
                this.terceroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("transaccion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public Transaccion[] transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.pasarela.fasttrack.com.co/comercios")]
    public partial class Tercero
    {
        
        private string tipo_documentoField;
        
        private string nro_documentoField;
        
        private string nombre1Field;
        
        private string nombre2Field;
        
        private string apellido1Field;
        
        private string apellido2Field;
        
        private string correo_electronicoField;
        
        private string telefonoField;
        
        private string celularField;
        
        private string direccionField;
        
        private string paisField;
        
        private string departamentoField;
        
        private string ciudadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tipo_documento
        {
            get
            {
                return this.tipo_documentoField;
            }
            set
            {
                this.tipo_documentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nro_documento
        {
            get
            {
                return this.nro_documentoField;
            }
            set
            {
                this.nro_documentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre1
        {
            get
            {
                return this.nombre1Field;
            }
            set
            {
                this.nombre1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre2
        {
            get
            {
                return this.nombre2Field;
            }
            set
            {
                this.nombre2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string apellido1
        {
            get
            {
                return this.apellido1Field;
            }
            set
            {
                this.apellido1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string apellido2
        {
            get
            {
                return this.apellido2Field;
            }
            set
            {
                this.apellido2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string correo_electronico
        {
            get
            {
                return this.correo_electronicoField;
            }
            set
            {
                this.correo_electronicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string celular
        {
            get
            {
                return this.celularField;
            }
            set
            {
                this.celularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string pais
        {
            get
            {
                return this.paisField;
            }
            set
            {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string departamento
        {
            get
            {
                return this.departamentoField;
            }
            set
            {
                this.departamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string ciudad
        {
            get
            {
                return this.ciudadField;
            }
            set
            {
                this.ciudadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.pasarela.fasttrack.com.co/comercios")]
    public partial class ConsultaResponse
    {
        
        private string error_codigoField;
        
        private string error_descripcionField;
        
        private string estado_codigoField;
        
        private string estado_descripcionField;
        
        private string cusField;
        
        private string fechaSolicitudField;
        
        private string fechaBancoField;
        
        private string cicloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string error_codigo
        {
            get
            {
                return this.error_codigoField;
            }
            set
            {
                this.error_codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string error_descripcion
        {
            get
            {
                return this.error_descripcionField;
            }
            set
            {
                this.error_descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string estado_codigo
        {
            get
            {
                return this.estado_codigoField;
            }
            set
            {
                this.estado_codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string estado_descripcion
        {
            get
            {
                return this.estado_descripcionField;
            }
            set
            {
                this.estado_descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cus
        {
            get
            {
                return this.cusField;
            }
            set
            {
                this.cusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string fechaSolicitud
        {
            get
            {
                return this.fechaSolicitudField;
            }
            set
            {
                this.fechaSolicitudField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string fechaBanco
        {
            get
            {
                return this.fechaBancoField;
            }
            set
            {
                this.fechaBancoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ciclo
        {
            get
            {
                return this.cicloField;
            }
            set
            {
                this.cicloField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.pasarela.fasttrack.com.co/comercios")]
    public partial class ConsultaRequest
    {
        
        private string usr_appsField;
        
        private string pwd_appsField;
        
        private string id_comercioField;
        
        private string id_transaccionField;
        
        private string fecha_transaccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string usr_apps
        {
            get
            {
                return this.usr_appsField;
            }
            set
            {
                this.usr_appsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string pwd_apps
        {
            get
            {
                return this.pwd_appsField;
            }
            set
            {
                this.pwd_appsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string id_comercio
        {
            get
            {
                return this.id_comercioField;
            }
            set
            {
                this.id_comercioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string id_transaccion
        {
            get
            {
                return this.id_transaccionField;
            }
            set
            {
                this.id_transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fecha_transaccion
        {
            get
            {
                return this.fecha_transaccionField;
            }
            set
            {
                this.fecha_transaccionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.pasarela.fasttrack.com.co/comercios")]
    public partial class PagoResponse
    {
        
        private string codigo_respuestaField;
        
        private string detalle_respuestaField;
        
        private string id_transaccionField;
        
        private string urlField;
        
        private string id_pagoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo_respuesta
        {
            get
            {
                return this.codigo_respuestaField;
            }
            set
            {
                this.codigo_respuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string detalle_respuesta
        {
            get
            {
                return this.detalle_respuestaField;
            }
            set
            {
                this.detalle_respuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string id_transaccion
        {
            get
            {
                return this.id_transaccionField;
            }
            set
            {
                this.id_transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string id_pago
        {
            get
            {
                return this.id_pagoField;
            }
            set
            {
                this.id_pagoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.pasarela.fasttrack.com.co/comercios")]
    public partial class Registro
    {
        
        private string id_productoField;
        
        private string detalleField;
        
        private string fecha_vencimientoField;
        
        private string referencia01Field;
        
        private string referencia02Field;
        
        private string estadoField;
        
        private string valorField;
        
        private string valor_ivaField;
        
        private string identificadorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id_producto
        {
            get
            {
                return this.id_productoField;
            }
            set
            {
                this.id_productoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string detalle
        {
            get
            {
                return this.detalleField;
            }
            set
            {
                this.detalleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fecha_vencimiento
        {
            get
            {
                return this.fecha_vencimientoField;
            }
            set
            {
                this.fecha_vencimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string referencia01
        {
            get
            {
                return this.referencia01Field;
            }
            set
            {
                this.referencia01Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string referencia02
        {
            get
            {
                return this.referencia02Field;
            }
            set
            {
                this.referencia02Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string valor_iva
        {
            get
            {
                return this.valor_ivaField;
            }
            set
            {
                this.valor_ivaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string identificador
        {
            get
            {
                return this.identificadorField;
            }
            set
            {
                this.identificadorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.pasarela.fasttrack.com.co/comercios")]
    public partial class Transaccion
    {
        
        private string id_transaccionField;
        
        private Registro[] registroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id_transaccion
        {
            get
            {
                return this.id_transaccionField;
            }
            set
            {
                this.id_transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("registro", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Registro[] registro
        {
            get
            {
                return this.registroField;
            }
            set
            {
                this.registroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.pasarela.fasttrack.com.co/comercios")]
    public partial class procesarPagoResponse
    {
        
        private PagoResponse pagoResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public PagoResponse PagoResponse
        {
            get
            {
                return this.pagoResponseField;
            }
            set
            {
                this.pagoResponseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class procesarPagoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.pasarela.fasttrack.com.co/comercios", Order=0)]
        public FTPagoElectronicoService.procesarPago procesarPago;
        
        public procesarPagoRequest()
        {
        }
        
        public procesarPagoRequest(FTPagoElectronicoService.procesarPago procesarPago)
        {
            this.procesarPago = procesarPago;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class procesarPagoResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.pasarela.fasttrack.com.co/comercios", Order=0)]
        public FTPagoElectronicoService.procesarPagoResponse procesarPagoResponse;
        
        public procesarPagoResponse1()
        {
        }
        
        public procesarPagoResponse1(FTPagoElectronicoService.procesarPagoResponse procesarPagoResponse)
        {
            this.procesarPagoResponse = procesarPagoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.pasarela.fasttrack.com.co/comercios")]
    public partial class consultarEstado
    {
        
        private ConsultaRequest consultaRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ConsultaRequest ConsultaRequest
        {
            get
            {
                return this.consultaRequestField;
            }
            set
            {
                this.consultaRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.pasarela.fasttrack.com.co/comercios")]
    public partial class consultarEstadoResponse
    {
        
        private ConsultaResponse consultaResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ConsultaResponse ConsultaResponse
        {
            get
            {
                return this.consultaResponseField;
            }
            set
            {
                this.consultaResponseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarEstadoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.pasarela.fasttrack.com.co/comercios", Order=0)]
        public FTPagoElectronicoService.consultarEstado consultarEstado;
        
        public consultarEstadoRequest()
        {
        }
        
        public consultarEstadoRequest(FTPagoElectronicoService.consultarEstado consultarEstado)
        {
            this.consultarEstado = consultarEstado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarEstadoResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.pasarela.fasttrack.com.co/comercios", Order=0)]
        public FTPagoElectronicoService.consultarEstadoResponse consultarEstadoResponse;
        
        public consultarEstadoResponse1()
        {
        }
        
        public consultarEstadoResponse1(FTPagoElectronicoService.consultarEstadoResponse consultarEstadoResponse)
        {
            this.consultarEstadoResponse = consultarEstadoResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface FTPagoElectronicoServicePortTypeChannel : FTPagoElectronicoService.FTPagoElectronicoServicePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class FTPagoElectronicoServicePortTypeClient : System.ServiceModel.ClientBase<FTPagoElectronicoService.FTPagoElectronicoServicePortType>, FTPagoElectronicoService.FTPagoElectronicoServicePortType
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FTPagoElectronicoServicePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(FTPagoElectronicoServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), FTPagoElectronicoServicePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FTPagoElectronicoServicePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FTPagoElectronicoServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FTPagoElectronicoServicePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FTPagoElectronicoServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FTPagoElectronicoServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FTPagoElectronicoService.procesarPagoResponse1> FTPagoElectronicoService.FTPagoElectronicoServicePortType.procesarPagoAsync(FTPagoElectronicoService.procesarPagoRequest request)
        {
            return base.Channel.procesarPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FTPagoElectronicoService.procesarPagoResponse1> procesarPagoAsync(FTPagoElectronicoService.procesarPago procesarPago)
        {
            FTPagoElectronicoService.procesarPagoRequest inValue = new FTPagoElectronicoService.procesarPagoRequest();
            inValue.procesarPago = procesarPago;
            return ((FTPagoElectronicoService.FTPagoElectronicoServicePortType)(this)).procesarPagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FTPagoElectronicoService.consultarEstadoResponse1> FTPagoElectronicoService.FTPagoElectronicoServicePortType.consultarEstadoAsync(FTPagoElectronicoService.consultarEstadoRequest request)
        {
            return base.Channel.consultarEstadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FTPagoElectronicoService.consultarEstadoResponse1> consultarEstadoAsync(FTPagoElectronicoService.consultarEstado consultarEstado)
        {
            FTPagoElectronicoService.consultarEstadoRequest inValue = new FTPagoElectronicoService.consultarEstadoRequest();
            inValue.consultarEstado = consultarEstado;
            return ((FTPagoElectronicoService.FTPagoElectronicoServicePortType)(this)).consultarEstadoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FTPagoElectronicoServiceHttpSoap11Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.FTPagoElectronicoServiceHttpsSoap11Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.FTPagoElectronicoServiceHttpSoap12Endpoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.FTPagoElectronicoServiceHttpsSoap12Endpoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FTPagoElectronicoServiceHttpSoap11Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://zft2323:8281/services/FTPagoElectronicoService.FTPagoElectronicoServiceHtt" +
                        "pSoap11Endpoint");
            }
            if ((endpointConfiguration == EndpointConfiguration.FTPagoElectronicoServiceHttpsSoap11Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://zft2323:8244/services/FTPagoElectronicoService.FTPagoElectronicoServiceHt" +
                        "tpsSoap11Endpoint");
            }
            if ((endpointConfiguration == EndpointConfiguration.FTPagoElectronicoServiceHttpSoap12Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://zft2323:8281/services/FTPagoElectronicoService.FTPagoElectronicoServiceHtt" +
                        "pSoap12Endpoint");
            }
            if ((endpointConfiguration == EndpointConfiguration.FTPagoElectronicoServiceHttpsSoap12Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://zft2323:8244/services/FTPagoElectronicoService.FTPagoElectronicoServiceHt" +
                        "tpsSoap12Endpoint");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            FTPagoElectronicoServiceHttpSoap11Endpoint,
            
            FTPagoElectronicoServiceHttpsSoap11Endpoint,
            
            FTPagoElectronicoServiceHttpSoap12Endpoint,
            
            FTPagoElectronicoServiceHttpsSoap12Endpoint,
        }
    }
}
